#!/bin/bash
die() {
  echo "$0: $*" >&2
  exit 1
}

cd "$(dirname "$0")" ||:

# shellcheck disable=SC1091
. .venv/bin/activate

if [[ -n "$CI" ]]; then
  ruff format --check || die "ruff format --check failed"
  ruff check || die "ruff check failed"
else
  ruff format || die "ruff format failed"
  ruff check --fix || die "ruff check --fix failed"
fi
mypy . || die "mypy failed"
