[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tomllint"
version = "1.0.0"
description = "A simple TOML linter."
authors = [{ name = "Will Bradley" }]

[tool.ruff]
line-length = 100

[project.scripts]
tomllint = "tomllint.main:main"
